language: java
jdk:
- oraclejdk8

#env:
#  - stage=QA deploy_dir=staging repo_url=https://github.com/RajeshkumarAyyadurai/securitytestv1.0.git

# Development source code would have already checkout from Github repository 
#as its already implicitly configured as part of travis configuration

# Installing required libs/softwares which are not already exist in machine
install:
- sudo apt-get install software-properties-common
- sudo apt-add-repository -y ppa:ansible/ansible
- sudo apt-get update
- sudo apt-get install ansible
- sudo apt install unzip

# Adding required privileges to the files before build
before_script:
# Deployment directory for staging environment
#- sudo mkdir /etc/ansible/$deploy_dir
#- sudo chmod 777 /etc/ansible/$deploy_dir
- sudo chmod 700 $TRAVIS_BUILD_DIR/deploy/tomcat.pem
- sudo chmod 777 $TRAVIS_BUILD_DIR/deploy/$deploy_dir/ansible.cfg
- sudo mv -f $TRAVIS_BUILD_DIR/deploy/$deploy_dir/ansible.cfg /etc/ansible/ansible.cfg
- sudo chmod 777 $TRAVIS_BUILD_DIR/deploy/$deploy_dir/hosts
- sudo mv -f $TRAVIS_BUILD_DIR/deploy/$deploy_dir/hosts /etc/ansible/hosts
- sudo chmod 777 $TRAVIS_BUILD_DIR/deploy/$deploy_dir/warDeploy.yml
- sudo mv -f $TRAVIS_BUILD_DIR/deploy/$deploy_dir/warDeploy.yml /etc/ansible/warDeploy.yml
 
# Executes build actions and creates java package in the form of WAR
script:
- mvn clean package
- cd /home/travis/build/RajeshkumarAyyadurai/
- ls
- cd /etc/ansible
- ls
- cat hosts

before_deploy:
- sudo chmod 777 TRAVIS_BUILD_DIR/scripts/deploy.sh

deploy:
  - provider: script
    script: TRAVIS_BUILD_DIR/scripts/deploy.sh staging
    on:
      branch: master
  - provider: script
    script: TRAVIS_BUILD_DIR/scripts/deploy.sh production
    on:
      branch: master

# Sends slack notification about the build and its status
notifications:
 slack:
  on_failure: always
  on_success: always
  rooms:
  - sot-neustar:hAZy7jMtJpHHnkjpDPDsYIlD
  template:
  - "Build(#%{build_number}) triggered by %{author} %{result} in %{duration}"
  - "Repository/Branch : %{repository_name}/%{branch}"
  - "Commit : %{commit_message}"
  - "Build URL : %{build_url}"