language: java
jdk:
- oraclejdk8

env:
  - stage=QA deploy_dir=staging repo_url=https://github.com/RajeshkumarAyyadurai/securitytestv1.0.git
  - stage=Production deploy_dir=prod repo_url=https://github.com/RajeshkumarAyyadurai/securitytestv1.0.git

# Development source code would have already checkout from Github repository 
#as its already implicitly configured as part of travis configuration

# Installing required libs/softwares which are not already exist in machine
install:
- sudo apt-get install software-properties-common
- sudo apt-add-repository -y ppa:ansible/ansible
- sudo apt-get update
- sudo apt-get install ansible
- sudo apt install unzip

# Adding required privileges to the files before build
before_script:
# Deployment directory for staging environment
#- sudo mkdir /etc/ansible/$deploy_dir
#- sudo chmod 777 /etc/ansible/$deploy_dir
- sudo chmod 700 $TRAVIS_BUILD_DIR/deploy/tomcat.pem
- sudo chmod 777 $TRAVIS_BUILD_DIR/deploy/$deploy_dir/ansible.cfg
- sudo mv -f $TRAVIS_BUILD_DIR/deploy/$deploy_dir/ansible.cfg /etc/ansible/ansible.cfg
- sudo chmod 777 $TRAVIS_BUILD_DIR/deploy/$deploy_dir/hosts
- sudo mv -f $TRAVIS_BUILD_DIR/deploy/$deploy_dir/hosts /etc/ansible/hosts
- sudo chmod 777 $TRAVIS_BUILD_DIR/deploy/$deploy_dir/warDeploy.yml
- sudo mv -f $TRAVIS_BUILD_DIR/deploy/$deploy_dir/warDeploy.yml /etc/ansible/warDeploy.yml
 
# Executes build actions and creates java package in the form of WAR
script:
- mvn clean package
- cd /home/travis/build/RajeshkumarAyyadurai/
- ls
- cd /etc/ansible
- ls
- cat hosts

# Deploys created WAR into AWS EC2 tomcat machine
after_success:
- cd /etc/ansible
- ansible-playbook warDeploy.yml
- sleep 5m

# Checks out QA source code explicitly from github repository
# Executes funtional integration tests when deployment is success
after_script:
- sudo mkdir /home/travis/build/RajeshkumarAyyadurai/$deploy_dir/
- sudo chmod 777 /home/travis/build/RajeshkumarAyyadurai/$deploy_dir
- cd /home/travis/build/RajeshkumarAyyadurai/$deploy_dir/
- git clone $repo_url
- cd /home/travis/build/RajeshkumarAyyadurai/$deploy_dir/securitytestv1.0/
- ls -l /home/travis/build/RajeshkumarAyyadurai/$deploy_dir/securitytestv1.0/lib/drivers/phantomjs
- chmod 755 /home/travis/build/RajeshkumarAyyadurai/$deploy_dir/securitytestv1.0/lib/drivers/phantomjs
- cd /home/travis/build/RajeshkumarAyyadurai/$deploy_dir/securitytestv1.0/
- mvn test

# Sends slack notification about the build and its status
notifications:
 slack:
  on_failure: always
  on_success: always
  rooms:
  - sot-neustar:hAZy7jMtJpHHnkjpDPDsYIlD
  template:
  - "Build(#%{build_number}) triggered by %{author} %{result} in %{duration}"
  - "Repository/Branch : %{repository_name}/%{branch}"
  - "Commit : %{commit_message}"
  - "Build URL : %{build_url}"