language: java
jdk:
- oraclejdk8
install:
- sudo apt-get install software-properties-common
- sudo apt-add-repository -y ppa:ansible/ansible
- sudo apt-get update
- sudo apt-get install ansible
script:
- mvn clean package
- cd /home/travis/build/RajeshkumarAyyadurai/
- ls
- git clone https://github.com/RajeshkumarAyyadurai/securitytestv1.0.git
- cd /home/travis/build/RajeshkumarAyyadurai/securitytestv1.0/
- ls
#after_script:
#- ansible-playbook -i $TRAVIS_BUILD_DIR/deploy/hosts $TRAVIS_BUILD_DIR/deploy/warDeploy.yml
