language: java
jdk:
- oraclejdk8
install:
- sudo apt-get install software-properties-common
- sudo apt-add-repository -y ppa:ansible/ansible
- sudo apt-get update
- sudo apt-get install ansible
script:
- mvn clean package
after_script:
- ansible-playbook -i hosts warDeploy.yml
