language: java
jdk:
- oraclejdk8
install:
- sudo apt-get install software-properties-common
- sudo apt-add-repository -y ppa:ansible/ansible
- sudo apt-get update
- sudo apt-get install ansible
script:
- mvn clean package
- cd /home/travis/build/RajeshkumarAyyadurai/
- ls
- git clone https://github.com/RajeshkumarAyyadurai/securitytestv1.0.git
- cd /home/travis/build/RajeshkumarAyyadurai/securitytestv1.0/
- ls -l /home/travis/build/RajeshkumarAyyadurai/securitytestv1.0/lib/drivers/phantomjs
- chmod 755 /home/travis/build/RajeshkumarAyyadurai/securitytestv1.0/lib/drivers/phantomjs
- ls
- mvn test
notifications:
  slack:
    on_failure: always
    on_success: always
    rooms:
    - sot-neustar:hAZy7jMtJpHHnkjpDPDsYIlD
    template:
    - "Build(#%{build_number}) triggered by %{author} %{result} in %{duration}"
    - "Repository/Branch : %{repository_name}/%{branch}"
    - "Commit : %{commit_message}"
    - "Build URL : %{build_url}"
#after_script:
#- ansible-playbook -i $TRAVIS_BUILD_DIR/deploy/hosts $TRAVIS_BUILD_DIR/deploy/warDeploy.yml
