- hosts: tomcatServers
  remote_user: ubuntu
  become_method: sudo
  become_user: root
  vars:
    warName: DDoSSecurityWeb-0.0.1-SNAPSHOT.war
    warRemotePath: /tmp
  tasks:
  - copy:
     src: /home/travis/build/RajeshkumarAyyadurai/security_app_build/target/{{ warName }}
     dest: /tmp/{{ warName }}
     owner: ubuntu
     group: ubuntu
     mode: 0755

  - name: Escalate permission to webapps folder in tomcat
    command: sudo chmod 755 /opt/tomcat/webapps
    
  - name: Create dir to deploy war
    command: sudo mkdir /opt/tomcat/webapps/travis
    
  - name: Enter into travis dir
    command: cd /opt/tomcat/webapps/travis/
  
  - name: Unzip WAR file
    command: jar -xvf /tmp/{{ warName }}
    notify:
        - restart tomcat7

  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent

  handlers:
    - name: Restart tomcat7
      service: name=tomcat7 state=restarted
